// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5XMnAYAUddYufnOL3HzwUO5u8KHnV3LM',
    appId: '1:364939892957:web:52bc3d781837f778926334',
    messagingSenderId: '364939892957',
    projectId: 'milkman-d0c74',
    authDomain: 'milkman-d0c74.firebaseapp.com',
    storageBucket: 'milkman-d0c74.firebasestorage.app',
    measurementId: 'G-0NR7DQ1DPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDS1JRgySA0W7tZdBWKfE3ePzeUcV8bv8',
    appId: '1:364939892957:android:24db765f528985a0926334',
    messagingSenderId: '364939892957',
    projectId: 'milkman-d0c74',
    storageBucket: 'milkman-d0c74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAanJhkSIzDPQXD7VykRWfjbjGVSRVC_wc',
    appId: '1:364939892957:ios:2ca09e2e8d2290c0926334',
    messagingSenderId: '364939892957',
    projectId: 'milkman-d0c74',
    storageBucket: 'milkman-d0c74.firebasestorage.app',
    iosBundleId: 'com.organicmandi.milkman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5XMnAYAUddYufnOL3HzwUO5u8KHnV3LM',
    appId: '1:364939892957:web:cf755b9dcb3dad3d926334',
    messagingSenderId: '364939892957',
    projectId: 'milkman-d0c74',
    authDomain: 'milkman-d0c74.firebaseapp.com',
    storageBucket: 'milkman-d0c74.firebasestorage.app',
    measurementId: 'G-4H2GCQDJX7',
  );

}